MercadoArtesanos/ArtesanosApp/urls.py
from django.urls import path
from .views import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
     path('', Home , name="home"),
     path('aboutUs', AboutUs, name="aboutUs"),
     path('contacto_artesano', Contacto_artesanos, name="contacto_artesanos"),
     path('productos', Productos, name="productos"),
     path('registro_artesanos', Registro_artesanos, name="registro_artesanos"),
     path('producto_principal/<id>', Producto_principal, name="producto_principal"),
     path('conf/<action>/<id>', Productos_conf, name="conf_producto"),
     path('conf', Listar_productos, name="listar_productos"),
     path('registro/', registrar_usuario, name="registro"),
     path('password_cambiada/', TemplateView.as_view(template_name='core/password_cambiada.html'), name='password_cambiada'),
     path('cambio_contrasena/', auth_views.PasswordChangeView.as_view(template_name='ArtesanosApp/cambiar_contrasena.html', success_url='/password_cambiada'), name='cambiar_password'),
     path('perfil_usuario/', perfil_usuario, name="perfil_usuario"),
     path('iniciar_sesion', iniciar_sesion, name="iniciar_sesion"),
     path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),




]

MercadoArtesanos/MercadoArtesanos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ArtesanosApp.urls')),
    path('api/', include('apirest.urls')),
    path('api/', include('apirest.urls')),
    
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MercadoArtesanos/apirest/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('producto_create/', Producto_create.as_view(), name="Producto_create"),
    path('producto_update/', Producto_update, name="Producto_update"),
    path('producto_read/<id>/', Producto_read, name="Producto_read"),
    path('producto_read/', Producto_read_all, name='Producto_read_all'),
    path('producto_delete/<id>/', Producto_delete, name="Producto_delete"),
    path('login/', login, name='login'),
]

MercadoArtesanos/ArtesanosApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Producto(models.Model):
        id = models.IntegerField(primary_key=True, verbose_name="Id producto") 
        nombre_producto = models.CharField(max_length=30 , blank=False , null=False , verbose_name="nombre del producto")
        precio = models.IntegerField(blank=False , null=False ,verbose_name="precio del producto")
        descripcion = models.CharField(max_length=1000 , blank=False , null=False , verbose_name = "descripcion del producto" )
        image = models.ImageField(upload_to ='images/' , default='nostock.jpg', blank=False , null=False  , verbose_name = "imagen del producto")
        def __str__(self):
            return self.nombre_producto



class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=80, blank=True, null=True, verbose_name="Rut")
    direccion = models.CharField(max_length=80, blank=True, null=True, verbose_name="Dirección")
 
    def __str__(self):
        return f"{self.user.username} - {self.user.first_name} {self.user.last_name} ({self.user.email})"

MercadoArtesanos/ArtesanosApp/forms.py
from django import forms
from django.forms import ModelForm, fields , Form
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

class CustomUserCreationForms(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "first_name" , "last_name" , "email" , "password1", "password2"]


class RegistrarUsuarioForm(UserCreationForm):
    rut = forms.CharField(max_length=80, required=True, label="Rut")
    direccion = forms.CharField(max_length=80, required=True, label="Dirección")
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'rut', 'direccion']

class PerfilUsuarioForm(Form):
    first_name = forms.CharField(max_length=150, required=True, label="Nombres")
    last_name = forms.CharField(max_length=150, required=True, label="Apellidos")
    email = forms.CharField(max_length=254, required=True, label="Correo")
    rut = forms.CharField(max_length=80, required=False, label="Rut")
    direccion = forms.CharField(max_length=80, required=False, label="Dirección")

    class Meta:
        fields = '__all__'

class IniciarSesionForm(Form):
    username = forms.CharField(widget=forms.TextInput(), label="Correo")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")
    class Meta:
        fields = ['username', 'password']

MercadoArtesanos/ArtesanosApp/views.py
from django.http import request
from django.shortcuts import render , redirect
from .models import Producto , PerfilUsuario
from django.contrib.auth.models import User
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required , permission_required



def AboutUs(request):
    return render(request , "ArtesanosApp/aboutUs.html")

def Contacto_artesanos(request):
    return render(request , "ArtesanosApp/contacto_artesanos.html")


def Home(request):
    data = {"lista":Producto.objects.all().order_by('id')[0:4] , "lista2":Producto.objects.all().order_by('precio')[5:9]}
    return render(request , "ArtesanosApp/home.html" , data)

def Producto_principal(request , id):
    producto = Producto.objects.get(id=id)
    data = {"lista": producto}
    return render(request , "ArtesanosApp/producto_principal.html", data)

def Productos(request):
    data = {"lista":Producto.objects.all().order_by('id')}
    return render(request , "ArtesanosApp/productos.html", data)

def Registro_artesanos(request):
    return render(request , "ArtesanosApp/registro_artesanos.html")


def Productos_conf(request, action, id):
    data = {"mesg": "", "form": ProductoForm, "action": action, "id": id}

    if action == 'ins':
        if request.method == "POST":
            form = ProductoForm(request.POST, request.FILES)
            if form.is_valid:
                try:
                    form.save()
                    messages.success(request,"¡El Producto fue creado correctamente!")
                    return redirect(to="listar_productos")
                except:
                    messages.warning(request,"No pueden existir productos con el mismo ID")

    elif action == 'upd':
        objeto = Producto.objects.get(id=id)
        if request.method == "POST":
            form = ProductoForm(data=request.POST, files=request.FILES, instance=objeto)
            if form.is_valid():
                form.save()
                messages.success(request, "¡El producto fue actualizado correctamente!")
                return redirect(to="listar_productos")
        data["form"] = ProductoForm(instance=objeto)

    elif action == 'del':
        try:
            Producto.objects.get(id=id).delete()
            return redirect(to="listar_productos")
        except:
            messages.error(request,"¡El Producto ya estaba eliminado!")
    data["list"] = Producto.objects.all().order_by('id')
    return render(request, "ArtesanosApp/conf_producto.html", data)

def Listar_productos(request):
    data = {"list":Producto.objects.all().order_by('id')}
    return render(request, 'ArtesanosApp/lista_productos.html', data)

def registro(request):
    data = {'form': CustomUserCreationForms}
    if request.method == 'POST':
        formulario = CustomUserCreationForms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Te has registrado correctamente")
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to="home")
    return render(request , 'registration/registro.html', data)


def perfil_usuario(request):
    data = {"mesg": "", "form": PerfilUsuarioForm}

    if request.method == 'POST':
        form = PerfilUsuarioForm(request.POST)
        if form.is_valid():
            user = request.user
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.email = request.POST.get("email")
            user.save()
            perfil = PerfilUsuario.objects.get(user=user)
            perfil.rut = request.POST.get("rut")
            perfil.direccion = request.POST.get("direccion")
            perfil.save()
            data["mesg"] = "¡Sus datos fueron actualizados correctamente!"

    perfil = PerfilUsuario.objects.get(user=request.user)
    form = PerfilUsuarioForm()
    form.fields['first_name'].initial = request.user.first_name
    form.fields['last_name'].initial = request.user.last_name
    form.fields['email'].initial = request.user.email
    form.fields['rut'].initial = perfil.rut
    form.fields['direccion'].initial = perfil.direccion
    data["form"] = form
    return render(request, "ArtesanosApp/perfil_usuario.html", data)

def registrar_usuario(request):
    if request.method == 'POST':
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            try:
                user = form.save()
                rut = request.POST.get("rut")
                direccion = request.POST.get("direccion")
                PerfilUsuario.objects.update_or_create(user=user, rut=rut, direccion=direccion)
                messages.success(request, "Se ha creado el usuario exitosamente")
                # DEJAMOS AL USUARIO AUTHENTICADO Y LOGEADO DE MANERA AUTOMÁTICA
                auth = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password1"])
                login(request, auth)
                return redirect(to="home")
            except:
                redirect(to="registrar_usuario")
    form = RegistrarUsuarioForm()
    
    return render(request, "ArtesanosApp/registrar_usuario.html", context={'form': form})

def iniciar_sesion(request):
    data = {"mesg": "", "form": IniciarSesionForm()}

    if request.method == "POST":
        form = IniciarSesionForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to="home")
                else:
                    data["mesg"] = "¡La cuenta o la password no son correctos!"
            else:
                data["mesg"] = "¡La cuenta o la password no son correctos!"
    return render(request, "ArtesanosApp/iniciar_sesion.html", data)

def cerrar_sesion(request):
    logout(request)
    return redirect(to="home")

MercadoArtesanos/ArtesanosApp/templates/ArtesanosApp/conf_producto.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-examples/assets/dist/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-dist/css/bootstrap.min.css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/carousel/" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-dist/css/bootstrap.min.css.map" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/conf_producto.css">
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/stylefooter.css" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/style_header.css" />
    <script src="../../static/ArtesanosApp/js/sweet_alert.js"></script>
    <title>Mercado Artesanos</title>

  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class=" navbar navbar-expand-md  fixed-top nav_color">
        <a class="navbar-brand" href="{% url 'home' %}"
          ><img src="../../static/ArtesanosApp/icons/tienda-en-linea.png" alt="Mercado artesanos" height="50px"
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Inicio </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'productos' %}">Productos</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacto_artesanos' %}">Contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aboutUs' %}">Acerca de nosotros</a>
            </li>
            {% if user.is_authenticated  %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'listar_productos' %}">configurar productos</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated  %}
          <li><a class="btn_sesion" href="{% url 'logout' %}">cerrar sesión</a></li>
          <li><a class="btn_sesion" href="#">@{{ user.username}}</a></li>

          {% else %}  
          <li><a class="btn_sesion" href="{% url 'login' %}">iniciar sesión</a></li>  
          <li><a class="btn_sesion" href="{% url 'registro' %}">registrate</a></li>  
          {% endif %}
            </select>
          </form>
        </div>
      </nav>
    </header>
    <!-- SWEET ALERT2 -->
    <script>
      function eliminaProducto(id){
        Swal.fire({
          "title": "¿Estas seguro?",
          "text":"Esta acción no se puede deshacer",
          "icono":"question",
          "showCancelButton":true,
          "cancelButtonText":"No , Cancelar",
          "confirmButtonText":"Si , Eliminar",
          "reverseButtons":true,
          "confirmButtonColor":"#FF0000",
          "cancelButtonColor":"#218838"
      
        })
        .then(function(result){
          if(result.isConfirmed){
            window.location.href = "/conf/del/"+id
          }
        })
      }
      </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
        {% for m in messages %}
        <script>
          Swal.fire({
            "title":"Atencion",
            "text":"{{m}}",
            "icon":"warning"
          })
        </script>
        {% endfor %}
    {% endif %}

    <div class="container">
        <br><br><br><br>
      <h1 style="text-align: center !important">Mantenedor de Productos</h1>
      
      {% if perms.ArtesanosApp.add_producto %}
      {% if form  %}
      <form method="POST" action="" enctype="multipart/form-data" id="formulario">
        <div class="form-group">{% csrf_token %} {{ form|crispy }}</div>
        <input type="submit"  class="btn btn-primary btnwidth" id="id_guardar" value="Guardar" />
        <!-- <input type="reset" class="btn btn-primary btnwidth" id="id_nuevo" value="Nuevo"> -->
        
        {% if id != '-1' %}
        <a class="btn btn-danger btnwidth" href="{% url 'conf_producto' 'del' id %}">Eliminar</a>
        {% endif %}
        {% endif %}
        
        
    </form>
    <br><br><br><br><br><br>
    
    {% endif %} {% if list %}
      <table id="tabla_datos " class="table">
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Nombre Producto</th>
            <th>Precio</th>
            <th>Descripción</th>
            <th>Imagen</th>
            {% if perms.ArtesanosApp.change_producto %}
            <th class="titulo_boton">Editar</th>
            {% endif %}
            {% if perms.ArtesanosApp.delete_producto %}
            <th class="titulo_boton">Eliminar</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for pd in list %}
          <tr >
            <td class="align-middle" >{{ pd.id }}</td>
            <td class="align-middle">{{ pd.nombre_producto }}</td>
            <td class="align-middle">{{ pd.precio }}</td>
            <td class="align-middle">{{ pd.descripcion }}</td>
            <td><img src="/media/{{ pd.image }}" class="imagen_mini" alt="" /></td>
            <td class="align-middle">
              {% if perms.ArtesanosApp.change_producto %}
              <a href="{% url 'conf_producto' 'upd' pd.id %}" class="btn btn-primary btn-sm  ">Editar</a>
              {% endif %}
            </td>
            <td class="align-middle">
              {% if perms.ArtesanosApp.delete_producto %}
              <a  class="btn btn-danger btn-sm " onclick="eliminaProducto({{ pd.id }})">Eliminar</a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
      <br />
    </div>

    <!-- SWEET ALERT2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <br><br><br><br>
    <footer class="footer1">
      <div class="container">
        <div class="row1">
          <div class="footer-col">
            <h4>ubicacion</h4>
            <ul>
              <li><p>Ricardo Matte Pérez 0270 Valparaiso</p></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>contacto</h4>
            <ul>
              <li><p>wsp:+56956872415</p></li>
              <li><p>MercadoArtesanos@contacto.cl</p></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>acceso rapido</h4>
            <ul>
              <li><a href="{% url 'home' %}">inicio</a></li>
              <li><a href="{% url 'productos' %}">productos</a></li>
              <li><a href="{% url 'contacto_artesanos' %}">contáctenos</a></li>
              <li><a href="{% url 'aboutUs' %}">acerca de nostros</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>Redes sociales</h4>
            <div class="social-links">
              <a href="https://es-la.facebook.com/pg/hotelcesarnic/posts/?ref=page_internal"
                ><img height="50px" src="../../static/ArtesanosApp/icons/facebook.png"
              /></a>
              <a href="https://twitter.com/sheratonhotels?lang=es"
                ><img height="50px" src="../../static/ArtesanosApp/icons/gorjeo.png"
              /></a>
              <a href="https://www.instagram.com/sheratonscl/?hl=es-la"
                ><img height="50px" src="../../static/ArtesanosApp/icons/instagram.png"
              /></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

MercadoArtesanos/ArtesanosApp/templates/ArtesanosApp/lista_productos.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-examples/assets/dist/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-dist/css/bootstrap.min.css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/carousel/" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/bootstrap/bootstrap-4.6.0-dist/css/bootstrap.min.css.map" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/conf_producto.css">
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/stylefooter.css" />
    <link rel="stylesheet" href="../../static/ArtesanosApp/style/style_header.css" />
    <script src="../../static/ArtesanosApp/js/sweet_alert.js"></script>
    <title>Mercado Artesanos</title>
  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class=" navbar navbar-expand-md  fixed-top nav_color">
        <a class="navbar-brand" href="{% url 'home' %}"
          ><img src="../../static/ArtesanosApp/icons/tienda-en-linea.png" alt="Mercado artesanos" height="50px"
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Inicio </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'productos' %}">Productos</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacto_artesanos' %}">Contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aboutUs' %}">Acerca de nosotros</a>
            </li>
            {% if user.is_authenticated  %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'listar_productos' %}">configurar productos</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          {% if user.is_authenticated  %}
          <li><a class="btn_sesion" href="{% url 'cerrar_sesion' %}">cerrar sesión</a></li>
          <li><a class="btn_sesion" href="{% url 'perfil_usuario' %}">@{{ user.username}}</a></li>

          {% else %}  
          <li><a class="btn_sesion" href="{% url 'iniciar_sesion' %}">iniciar sesión</a></li>  
          <li><a class="btn_sesion" href="{% url 'registro' %}">registrate</a></li>  
          {% endif %}
            </select>
          </form>
        </div>
      </nav>
    </header>
    <!-- SWEET ALERT -->
    <script>
      function eliminaProducto(id){
        Swal.fire({
          "title": "¿Estas seguro?",
          "text":"Esta acción no se puede deshacer",
          "icono":"question",
          "showCancelButton":true,
          "cancelButtonText":"No , Cancelar",
          "confirmButtonText":"Si , Eliminar",
          "reverseButtons":true,
          "confirmButtonColor":"#FF0000",
          "cancelButtonColor":"#218838"
      
        })
        .then(function(result){
          if(result.isConfirmed){
            window.location.href = "/conf/del/"+id
          }
        })
      }
      </script>
     
    
   
  


    <div class="container">
        <br><br><br><br>
      <h1 style="text-align: center !important">Mantenedor de Productos</h1>
            
      
    <br><br><br><br><br><br>
    {% if perms.ArtesanosApp.add_producto %}
    <a class="btn btn-success btnwidth float-right m-2" href="{% url 'conf_producto' 'ins' -1 %}">Agregar nuevo producto</a>
    {% endif %}
    {% if list %}
      <table id="tabla_datos " class="table">
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Nombre Producto</th>
            <th>Precio</th>
            <th>Descripción</th>
            <th>Imagen</th>
            {% if perms.ArtesanosApp.change_producto %}
            <th class="titulo_boton">Editar</th>
            {% endif %}
            {% if perms.ArtesanosApp.delete_producto %}
            <th class="titulo_boton">Eliminar</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for pd in list %}
          <tr >
            <td class="align-middle" >{{ pd.id }}</td>
            <td class="align-middle">{{ pd.nombre_producto }}</td>
            <td class="align-middle">{{ pd.precio }}</td>
            <td class="align-middle">{{ pd.descripcion }}</td>
            <td><img src="/media/{{ pd.image }}" class="imagen_mini" alt="" /></td>
            <td class="align-middle">
              {% if perms.ArtesanosApp.change_producto %}
              <a href="{% url 'conf_producto' 'upd' pd.id %}" class="btn btn-primary btn-sm  ">Editar</a>
              {% endif %}
            </td>
            <td class="align-middle">
              {% if perms.ArtesanosApp.delete_producto %}
              <a  class="btn btn-danger btn-sm " onclick="eliminaProducto({{ pd.id }})">Eliminar</a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
      <br />
    </div>

     <!-- SWEET ALERT2 -->
     <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
     {% if messages %}
     {% for m in messages %}
        <script>
          Swal.fire({
            "title":"Felicitaciones",
            "text":"{{m}}",
            "icon":"success"
          })
        </script>
      {% endfor %}
      {% endif %}
        <br><br><br><br>
      <footer class="footer1">
        <div class="container">
          <div class="row1">
            <div class="footer-col">
              <h4>ubicacion</h4>
              <ul>
                <li><p>Ricardo Matte Pérez 0270 Valparaiso</p></li>
              </ul>
            </div>
            <div class="footer-col">
              <h4>contacto</h4>
              <ul>
                <li><p>wsp:+56956872415</p></li>
                <li><p>MercadoArtesanos@contacto.cl</p></li>
              </ul>
            </div>
            <div class="footer-col">
              <h4>acceso rapido</h4>
              <ul>
                <li><a href="{% url 'home' %}">inicio</a></li>
                <li><a href="{% url 'productos' %}">productos</a></li>
                <li><a href="{% url 'contacto_artesanos' %}">contáctenos</a></li>
                <li><a href="{% url 'aboutUs' %}">acerca de nostros</a></li>
              </ul>
            </div>
            <div class="footer-col">
              <h4>Redes sociales</h4>
              <div class="social-links">
                <a href="https://es-la.facebook.com/pg/hotelcesarnic/posts/?ref=page_internal"
                  ><img height="50px" src="../../static/ArtesanosApp/icons/facebook.png"
                /></a>
                <a href="https://twitter.com/sheratonhotels?lang=es"
                  ><img height="50px" src="../../static/ArtesanosApp/icons/gorjeo.png"
                /></a>
                <a href="https://www.instagram.com/sheratonscl/?hl=es-la"
                  ><img height="50px" src="../../static/ArtesanosApp/icons/instagram.png"
                /></a>
              </div>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>